# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

r:
  - oldrel
  - release

# work around temporary travis + R 3.5 bug
# https://github.com/tidyverse/ggplot2/blob/master/.travis.yml#L18
r_packages: devtools

env:
  - PACKAGE_VERSION="1.0.0.9000"

os:
  - linux
  - osx

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'
  - make test-nocache
  - Rscript -e 'lintr::lint_package()'
